services:
- type: web
  name: cravebreaker-bot
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  plan: free
  envVars:
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: SESSION_SECRET
    generateValue: true
  healthCheckPath: /health