[deployment]
run = "python main.py"
deploymentTarget = "cloudrun"
entrypoint = "main.py"
publicPort = 5000

[deployment.env]
PORT = "5000"
HOST = "0.0.0.0"
PYTHONPATH = "."

[deployment.health]
path = "/"
timeout = 30

[deployment.build]
modules = ["python-3.11"]

[deployment.resources]
cpu = 1
memory = 512